---
- hosts: qaservers
  become: true
  tasks:
    - name: ensure apache is at the latest version
      yum: name=httpd state=latest
    - name: start apache
      service:
          name: httpd
          state: started
